spring:
  sql:
    init:
      mode: always
  datasource:
    password: password
    url: jdbc:h2:file:./db/liberty
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false