
spring:
  datasource:
    password:
    url: jdbc:h2:/tmp/liberty
    username: user
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true