
spring:
  datasource:
    password:
    url: jdbc:postgresql://localhost:5432/liberty
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true